### ISSUE TITLE
Run command

### ISSUE THREAD

**Issue by mahmoodn** [yuhc/gpu-parboil#2]
Regarding the run command `./parboil run     cutcp cuda default`, actually there is no `default` input. It may was for older versions. Currently there are large and small datasets.

However, when I run `./parboil run     cutcp cuda small`, I get an error in `cuda.mk`. I have added more debug lines as below:

```
        @echo "Resolving CUDA runtime library..."
        @echo "`pwd`"
        @echo "$(RUNTIME_ENV)"
        @echo "$(CUDA_LIB_PATH)"
        @echo "$(BIN)"
        @$(shell echo $(RUNTIME_ENV)) LD_LIBRARY_PATH=$(CUDA_LIB_PATH) ldd $(BIN) | grep cuda

```

And in the output I see:
```
Resolving CUDA runtime library...
/home/mahmood/suites/parboil/benchmarks/cutcp

/usr/local/cuda/lib64
build/cuda_default/cutcp
/home/mahmood/suites/parboil/common/mk/cuda.mk:71: recipe for target 'run' failed
make: *** [run] Error 1
```
Actually, `$(RUNTIME_ENV)` is empty. I haven't figure out what is that. Have you seen this before?

**Comment by yuhc** [comment]
I don't think `RUNTIME_ENV` really matters. It seems supposed to be set in your shell and can be empty.
The output doesn't tell much. Why not execute lines around `cuda.mk:71` in shell manually to get some useful debugging information?

**Comment by mahmoodn** [comment]
This doesn't work
```
$ build/cuda_default/cutcp ../../datasets/cutcp/small/input/watbox.sl40.pqr
Expecting one input file
```
I have to read all source files for argv and see how to run the programs. Isn't there any better option? This may insert fault in analyses.

**Comment by yuhc** [comment]
That simply means the input file is missing or the path is wrong.

BTW, it's always a better idea to contact the original author or active
developer. I don't really use this benchmark anymore in my projects.

Best,
Hangchen

--
Dept. of Computer Science
University of Texas-Austin
http://cs.utexas.edu/~hyu
Email: hyu@cs.utexas.edu

**Comment by topcuburak** [comment]
Hey @mahmoodn, have you solved this problem? I am facing the same issue now. The RUNTIME_ENV path return with nothing.

**Comment by mahmoodn** [comment]
@topcuburak 
As far as I remember, if you comment two `RUNTIME_ENV` lines in the run section, you can fix the problem.
